--1
CREATE TABLE
	CATALOG_FILES (_id INTEGER PRIMARY KEY,
	    ASIN VARCHAR(255) NOT NULL,
	    FILE_LOCATION_URI VARCHAR(255) NOT NULL,
	    FILE_SIZE_BYTES INTEGER,
	    FILE_TYPE VARCHAR(255) NOT NULL,
	    CREATION_DATE_MS_UTC INTEGER NOT NULL,
	    FILE_SUB_TYPE VARCHAR(255));
CREATE INDEX INDEX_ASIN ON CATALOG_FILES(ASIN);
CREATE INDEX INDEX_ASIN_FILE_TYPE ON CATALOG_FILES(ASIN, FILE_TYPE);

